### ISSUE TITLE
php error

### ISSUE THREAD

**Issue by ildarkhasanshin** [bobthecow/sublime-sane-snippets#9]
---
description: server_desc
tabTrigger:  server
scope:       source.php
---
$_SERVER["SERVER_NAME"]

result:
["SERVER_NAME"]

must be:
$_SERVER["SERVER_NAME"]

reason:
you want to automatically add \ to server.sane.sublime-snippet
\$_SERVER["SERVER_NAME"]

**Comment by bobthecow** [comment]
We don't want to automatically add escaping to `$`. In sublime snippets (and sane snippets) `$` has a meaning, and is super useful. If we escape it, we can't use placeholders, or replacements, or selection or any number of things that snippets should have. Just add the `\` yourself in cases like this :)

**Comment by ildarkhasanshin** [comment]
rule:
after "$" follow "{" - not escape

**Comment by bobthecow** [comment]
It's not that simple. Check out all the `$` here:

https://github.com/bobthecow/sublime-sane-snippets/blob/master/Test/highlight_test.sane_snippet

Automatically escaping `$` in sane snippets would be insane. Users would have no idea when it would work and when it wouldn't, and it would give them a false sense of security until it failed. We might as well turn on `magic_quotes_gpc` ;)
